# do not touch this line
configVersion: 2

name: matrixstatus
description: sends health checks
keywords: ''
sensors:
  - temperature
  - uv
  - humidity
  - pressure
cpu:
  type: monitor
  key: cpu
  display: digit
  format: round
  label: cpu
  